<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    /**
     * @var array
     */
    protected $fillable = [
       'name', 'slug'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function posts()
    {
        return $this->belongsToMany(Post::class);
    }

    public function save(array $options = [])
    {
        if(empty($this->slug)){
            $this->slug = urlencode(str_replace(' ', '_', $this->name));
        }
        return parent::save($options); // TODO: Change the autogenerated stub
    }
}
